### ISSUE TITLE
Possible to remove docker-compose and just use vanilla dockerfile?

### ISSUE THREAD

**Issue by malerba423** [carehart/awesome-cf-compose#6]
Howdy Charlie,
Apologies for the "issue" here as it's not actually an issue but rather a simple docker-noob question... but do you know how I would launch this project just using a vanilla dockerfile and not using docker-compose? I unfortunately think my choice of fly.io as my container host basically mandates that i use fly.toml instead of docker-compose.yml (and the fly.toml can reference a vanilla dockerfile, but not a docker-compose.yml).

Thanks in advance for any help!
Cheers,
Joel

**Comment by malerba423** [comment]
OR conversely... would you maybe have a recommendation as to a host that works with the repo as you currently have it configured? I'm not beholden to fly.io but i DO like it's simplicity. 

Thanks again!
Cheers,
Joel

**Comment by carehart** [comment]
Yes, see the example I offer (as one of the many links listed on the front page/readme):

ColdFusion as a Dockerfile only (For people who don't plan to or can't use Compose)

**Comment by malerba423** [comment]
ahhh, **of course** you already had the example there and i just missed it 🤦. sorry for the unnecessary ask / thanks for taking the time to reply, your help is much appreciated!

**Comment by malerba423** [comment]
ahhh, **of course** you already had the example there and i just missed it 🤦. sorry for the unnecessary ask / thanks for taking the time to reply, your help is much appreciated!
